source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'colorize'
gem 'closure-compiler'
gem 'sass', '~> 3.3.0'
gem 'guard'
gem 'guard-shell'
gem 'guard-compass'
gem 'guard-livereload'
gem 'httparty'
gem 'rb-readline'
gem 'wdm'
gem 'smusher'
gem 'coffee-script'
gem 'highline'
