require 'JSON'
require 'pp'
require 'colorize'
require 'closure-compiler'
require 'fileutils'

task default: :build

directory '../resources/css'
directory '../resources/js'
directory '../resources/img'
directory '../resources/fonts'

desc 'Build all resources'
task build: [
  'build:css',
  'build:js',
  'build:fonts',
  'build:img'
] do
  puts 'Resources have been built!'.magenta
  puts "Total size of app.css is now #{file_size_in_kb('../resources/css/app.css')} kb"
  puts "Total size of app.js is now #{file_size_in_kb('../resources/js/app.js')} kb"
end

namespace :build do
  desc 'Build css'
  task css: ['../resources/css'] do
    system "compass compile"
  end

  desc 'Minify and concatenate js'
  task js: ['../resources/js'] do
    compilation_levels = {
      simple: 'SIMPLE_OPTIMIZATIONS',
      advanced: 'ADVANCED_OPTIMIZATIONS',
      whitespace: 'WHITESPACE_ONLY'
    }
    contents = Closure::Compiler.new(compilation_level: compilation_levels[:simple]).compile_files paths_to_js_files
    File.open "../resources/js/app.js", "w" do |file|
      file.write contents
    end
    puts "overwrite".yellow + " ../resources/js/app.js"
  end

  desc 'Copy images'
  task img: ['../resources/img'] do
    remove_files_in '../resources/img'
    img_paths.each {|ip| FileUtils.copy_file ip, "../resources/#{ip}" }
  end

  desc 'Copy fonts'
  task fonts: ['../resources/fonts'] do
    remove_files_in '../resources/fonts'
    font_paths.each {|fp| FileUtils.copy_file fp, "../resources/#{fp}" }
  end
end

task :replace_paths do
  JSON.parse(File.read 'paths.json').each do |key, value|
    if File.exists? "../#{key}"
      contents = File.read "../#{key}"
      contents.gsub! value["replace"], value["with"]
      File.open "../#{key}", "w" do |file|
        file.write contents
      end
    end
  end
end

desc "Remove console.log statements from app.js"
task :remove_console_logs do
  app_js_path = '../resources/js/app.js'
  contents = File.read app_js_path if File.exists? app_js_path
  contents.gsub!(/console\.log\(.+?\);?/, '')
  File.open app_js_path, "w" do |file|
    file.write contents
  end
end

Kernel.trap("EXIT") do
  Rake::Task[:replace_paths].execute
end

def js_components
  JSON.parse File.read File.join 'js', 'components.json'
end

def paths_to_js_files
  js_components.map {|name, path| File.join('js', path) }
end

def file_size_in_kb file_path
  File.size(file_path)./(1024.0).round
end

def font_paths
  Dir["fonts/**/*"].map {|path| path unless path.include?("config.json") }.compact
end

def img_paths
  Dir["img/**/*"]
end

def remove_files_in folder_path
  Dir["#{folder_path}/**/*"].each {|file| FileUtils.rm_rf file }
end
